apiVersion: v1
kind: Service
metadata:
  name: hello-cname
  namespace: net-demo-isolated
spec:
  type: ExternalName
  externalName: hello.net-demo-isolated.svc.cluster.local
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello-app
  namespace: net-demo-isolated
spec:
  ingressClassName: haproxy
  rules:
  - host: ingress.hello.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-cname
            port:
              number: 8080